### ISSUE TITLE
ViewPort Width Issue

### ISSUE THREAD

**Issue by DarthBenro008** [UniAuth/uniauth.github.io#6]
There is a ViewPort Width Issue that causes extra white spacing and enables a horizontal scroll bar.

https://uniauth.co

![image](https://user-images.githubusercontent.com/31009634/106752329-538b7f80-6650-11eb-8dbd-e20db409e4b1.png)

**Comment by Abhijay007** [comment]
@YashKumarVerma sir can I work on this and sir can you please mention on which screen size this error occurs.

**Comment by YashKumarVerma** [comment]
I believe this was resolved. @DarthBenro008 could you confirm?

@Abhijay007 we're opening new issues as there are few fixes needed in the site. Keep an eye on the issues.

**Comment by Abhijay007** [comment]
> I believe this was resolved. @DarthBenro008 could you confirm?
> 
> @Abhijay007 we're opening new issues as there are few fixes needed in the site. Keep an eye on the issues.

definitely @YashKumarVerma sir  👍

**Comment by DarthBenro008** [comment]
@YashKumarVerma the issue still persists at 1024px width breakpoint.

At 1038px width:

![image](https://user-images.githubusercontent.com/31009634/108403700-00ffb500-7245-11eb-9404-918bee3197a2.png)

At 1023px width:

![image](https://user-images.githubusercontent.com/31009634/108403866-2f7d9000-7245-11eb-9bd9-58957d4c950a.png)

**Comment by YashKumarVerma** [comment]
Thank you for your help @DarthBenro008, 

@Abhijay007 please refer.

Also, there's no need to call as sir 😅

**Comment by Abhijay007** [comment]
> Thank you for your help @DarthBenro008,
> 
> @Abhijay007 please refer.
> 
> Also, there's no need to call as sir 😅

ok @YashKumarVerma 😅

**Comment by Abhijay007** [comment]
> @YashKumarVerma the issue still persists at 1024px width breakpoint.

also at 500px to nearly 900px
